name: "Publish to PyPI"

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  release-build:
    runs-on: ubuntu-latest
    
    environment:
      name: pypi
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      
      - name: Install uv
        run: pip install uv

      - name: Extract version from release tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"
      
      - name: Update version in pyproject.toml
        run: |
          sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$VERSION\"/" pyproject.toml
          echo "Updated pyproject.toml with version $VERSION"
          cat pyproject.toml | grep version     

      - name: Build package
        run: uv build
      
      - name: Publish to PyPI
        run: uv publish
