name: "Publish to PyPI"

on: push
#  release:
#    types: [published]

permissions:
  contents: read
  id-token: write  # Required for trusted publishing

jobs:
  release-build:
    runs-on: ubuntu-latest
    
    environment:
      name: pypi
      url: https://pypi.org/project/numpysocket/${{ github.event.release.name }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      
      - name: Install uv
        run: pip install uv
      
      - name: Build package
        run: uv build
      
      - name: Publish to PyPI
        run: uv publish
